### ISSUE TITLE
Персональное задание: Лесников Никита Алексеевич 3821Б1ПМОП3

### ISSUE THREAD

**Issue by dkurt** [UNN-ITMM-Software/devtools-course-practice#258]
@lesnikowka, 

Необходимо выполнить любую задачу в одном из популярных open source проектов. Это может быть как задача по коду, так и по документации. Требуется предоставить ссылку на открытый пулл реквест. Если полезность вклада в выбранный проект не вызывает вопросов - метка "delayed" будет снята с вашей лабораторной работы.

**Comment by lesnikowka** [comment]
https://github.com/lesnikowka/FFmpeg/pull/1

Пулл реквест делаю в форкнутый репозиторий, т.к ffmpeg не работают через пулл реквесты. "Patches should be submitted to the ffmpeg-devel mailing list using git format-patch or git send-email. Github pull requests should be avoided because they are not part of our review process and will be ignored."

**Comment by dkurt** [comment]
@lesnikowka, понимаю, патчи через mailing list сложнее проводить, но может есть шанс что попробуете? Чтобы получить комментарий от разработчиков.

**Comment by lesnikowka** [comment]
разработчики не примут изменение, так как в нем не было необходимости, это просто моя инициатива.
